#pragma once

#include "nop.h"

#include "Debug_Application.h"
#include "RT_TlmDispatcher.h"
#include "RT_CmdDispatcher.h"
#include "TL_CmdDispatcher.h"
#include "AnomalyHandler.h"
#include "AppStatus.h"
#include "GS_DataHandler.h"
#include "UVC_app.h"
#include "MSN_PacketHandler.h"
#include "ADCS_PacketHandler.h"
#include "GNSS_receiver.h"
#include "STRX_update.h"
#include "EPS_update.h"
#include "IMU_update.h"
#include "OBC_TlmGenerator.h"
#include "Temperature.h"
#include "FRAM_TL_CmdDispatcher.h"
#include "RTC_update.h"
#include "Stored_TlmGenerator.h"