// AppRegistry.h

#ifndef _APPREGISTRY_h
#define _APPREGISTRY_h

#if defined(ARDUINO) && ARDUINO >= 100
	#include "arduino.h"
#else
	#include "WProgram.h"
#endif

typedef enum
{
	AR_NOP,
	AR_ANOMALY_HANDLER,
	AR_APP_STATU,
	AR_UVC,
	AR_TEMPERATURE_UPDATE,
	AR_GS_DATA_HANDLER,
	AR_TLM_GENERATOR,
	AR_RT_CMD,
	AR_TL_CMD,
	AR_RT_TLM,
	AR_FRAM_TLC,
	AR_STRX_UPDATE,
	AR_STX_TRANSMIT,
	AR_EPS_UPDATE,
	AR_IMU_UPDATE,
	AR_GNSS_RECEIVER,
	AR_ADCS_PACKET_HANDLER,
	AR_ADCS_CMD_FORWARD,
	AR_MSN_CMD_FORWARD,
	AR_MSN_PACKET_HANDLER,
	AR_RTC_UPDATE,
	AR_ST_TLM,
	AR_DBG_PACKET_HANDLER,
	AR_MSN_DR_ERASE_HANDLER,
	AR_PRINT_DBG_MESSAGE
} AR_APP_ID;

void AR_load_initial_settings(void);

#endif // APP_REGISTRY_H_

